versão : " 2.2 "  
serviços :
  nginx :
    estende :
      arquivo : ./nginx/docker-compose.yml
      serviço : nginx
    redes :
        - nginx
    depende_on :
        - " php "
    volumes :
        - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/config/app.vhost:/etc/nginx/conf.d/app.vhost
        - ./nginx/Logs/Nginx:/var/log/nginx
        - ../src/:/var/www/html
    portas :
        - " 80:80 "
        - " 443: 443 "

  php :
    estende :
      arquivo : ./php7.3/docker-compose.yml
      serviço : php
    redes :
        - nginx
        - db
    depende_on :
        - " postgres "
    volumes :
        - ../src/:/var/www/html

  postgres :
    estende :
      arquivo : ./postgres/docker-compose.yml
      serviço : postgres
    redes :
        - db
    portas :
        - " 5432: 5432 "
    ambiente :
        - POSTGRES_PASSWORD = postgres
        - POSTGRES_USER = postgres
        - POSTGRES_DB = projeto
    volumes :
        - ./postgres/var/lib/postgres:/var/lib/postgres

redes :
  nginx :
  db :
